version: '3.8'

services:
  frontend:
    build:
      context: ./notion-dashboard
    container_name: notion-frontend
    ports:
      - "3010:80"
    env_file:
      - ./notion-dashboard/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./notion-dashboard-backend
    container_name: notion-backend
    ports:
      - "3020:5000"
    env_file:
      - ./notion-dashboard-backend/.env
    environment:
      - PYTHONUNBUFFERED=1 
